### PR TITLE
Merge Conflicts Showing In MD files

### PR DESCRIPTION
**Pull request by wdifruscio**
Hi,

I was going through these exercises and noticed several >>>>>>> and HEAD when reading through the explanations.  Figured I would come and remove the unseen merge conflicts!

### CODE REVIEW

**Comment by denysdovhan** [comment]
Wow, I have no idea how I didn't noticed that. It's important, gonna merge and release new version ASAP.

**Comment by denysdovhan** [comment]
Published as `v1.3.2`!
Thanks for contributing!

**Comment by wdifruscio** [comment]
You're welcome! I finished the series today, great stuff!!

**Comment by denysdovhan** [comment]
Thanks ;)

**Pull request merged**
